name: Khulnasoft Cloud

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '15 21 * * 2'

jobs:
  build:
    name: Vulnerability Scan
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner against Khulnasoft Cloud
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          hide-progress: true
          format: 'table'

